'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/testService2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ciudadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private companyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contactoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private direccionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private paisField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tlfField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ciudad() As String
            Get
                Return Me.ciudadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ciudadField, value) <> true) Then
                    Me.ciudadField = value
                    Me.RaisePropertyChanged("ciudad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property company() As String
            Get
                Return Me.companyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.companyField, value) <> true) Then
                    Me.companyField = value
                    Me.RaisePropertyChanged("company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contacto() As String
            Get
                Return Me.contactoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.contactoField, value) <> true) Then
                    Me.contactoField = value
                    Me.RaisePropertyChanged("contacto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.direccionField, value) <> true) Then
                    Me.direccionField = value
                    Me.RaisePropertyChanged("direccion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                If (Object.ReferenceEquals(Me.idField, value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.paisField, value) <> true) Then
                    Me.paisField = value
                    Me.RaisePropertyChanged("pais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tlf() As String
            Get
                Return Me.tlfField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tlfField, value) <> true) Then
                    Me.tlfField = value
                    Me.RaisePropertyChanged("tlf")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ClienteIService")>  _
    Public Interface ClienteIService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClienteIService/nuevoCliente", ReplyAction:="http://tempuri.org/ClienteIService/nuevoClienteResponse")>  _
        Function nuevoCliente(ByVal cliente As ServiceReference1.Cliente) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClienteIService/editarCliente", ReplyAction:="http://tempuri.org/ClienteIService/editarClienteResponse")>  _
        Function editarCliente(ByVal cliente As ServiceReference1.Cliente) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClienteIService/eliminarCliente", ReplyAction:="http://tempuri.org/ClienteIService/eliminarClienteResponse")>  _
        Function eliminarCliente(ByVal id As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClienteIService/buscarCliente", ReplyAction:="http://tempuri.org/ClienteIService/buscarClienteResponse")>  _
        Function buscarCliente(ByVal id As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClienteIService/listarCliente", ReplyAction:="http://tempuri.org/ClienteIService/listarClienteResponse")>  _
        Function listarCliente() As ServiceReference1.Cliente()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClienteIServiceChannel
        Inherits ServiceReference1.ClienteIService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClienteIServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ClienteIService)
        Implements ServiceReference1.ClienteIService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function nuevoCliente(ByVal cliente As ServiceReference1.Cliente) As Integer Implements ServiceReference1.ClienteIService.nuevoCliente
            Return MyBase.Channel.nuevoCliente(cliente)
        End Function
        
        Public Function editarCliente(ByVal cliente As ServiceReference1.Cliente) As Integer Implements ServiceReference1.ClienteIService.editarCliente
            Return MyBase.Channel.editarCliente(cliente)
        End Function
        
        Public Function eliminarCliente(ByVal id As String) As Integer Implements ServiceReference1.ClienteIService.eliminarCliente
            Return MyBase.Channel.eliminarCliente(id)
        End Function
        
        Public Function buscarCliente(ByVal id As String) As Integer Implements ServiceReference1.ClienteIService.buscarCliente
            Return MyBase.Channel.buscarCliente(id)
        End Function
        
        Public Function listarCliente() As ServiceReference1.Cliente() Implements ServiceReference1.ClienteIService.listarCliente
            Return MyBase.Channel.listarCliente
        End Function
    End Class
End Namespace
