//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneExt
    {
        public int Id { get; set; }
        public int Department { get; set; }
        public string Nombre { get; set; }
        public string Ext { get; set; }
        public string Status { get; set; }
    
        public virtual Deparment Deparment { get; set; }
    }
}
